### ISSUE TITLE
cell flashing in React

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid-enterprise#10]
Hi, I tried to use the "enableCellChangeFlash", but I couldn't let it work.
Probably it is just not fully documented and I didn't get how it should work though.

Anyway, I'm using ag-grid with ag-grid-react, so I was expecting that when passing new data (in the "rowData" prop), the changed cells should have flashed.
But they are not.
Am I missing something?

**Comment by ceolter** [comment]
only happens in the following instances:
1) Calling rowNode.setDataValue(colKey, value) to set a value directly onto the rowNode
2) When editing a cell and editing is stopped, so that cell displays new value after editing.
3) Calling api.refreshCells(rowNodes, colIds) to inform grid data has changed (see Refresh docs).
4) Calling api.softRefreshView() to inform grid data has changed (see Refresh docs).
