### ISSUE TITLE
Class 'ClipboardService' incorrectly implements interface 'IClipboardService'

### ISSUE THREAD

**Issue by mpetkov** [ceolter/ag-grid-enterprise#4]
Here is the error:

`node_modules/ag-grid-enterprise/dist/lib/clipboardService.d.ts(2)
 Class 'ClipboardService' incorrectly implements interface 'IClipboardService'.
  Property 'copySelectedRangeToClipboard' is missing in type 'ClipboardService'.
`
Essentially IClipboardService has a required definition of copySelectedRangeToClipboard() which ClipboardService is not defining.

**Comment by ceolter** [comment]
it does implement this method, see here:
https://github.com/ceolter/ag-grid-enterprise/blob/master/src/clipboardService.ts#L206

i am surprised you are finding this, as the typescript compiler should complain about these things. anyway, i'm guessing it was missing, but is now fixed in master?

btw, you didn't mention the version you are on. however i've verified it's working in latest, so it is a bug, should be fixed in next release (which is about two weeks out).

**Comment by mpetkov** [comment]
@ceolter - I apologize, I was using version 4.0.3 and looks like it was fixed in later versions.  I will update it right now.  Thank you for the quick reply.

**Comment by ceolter** [comment]
no worries :)
