### ISSUE TITLE
Get row node by id

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#53]
Since version 5.1.2, ag-grid now has a call back getRowNodeId().

Is there now a way to get node object from id? I am using this to implement custom checkbox. I would like to store the node id with the checkbox and get the node from the node id. Right now, i am storing the node reference with the checkbox through jquery.data.

I would also appreciate if you have a suggestion for an alternative.

Thanks

**Comment by ceolter** [comment]
i assume you are talking about cellRenderer? if yes, then node is passed as a param, and the id is in the node.

another way, which i don't recommend, but you might want, is to also use api.getBusinessKeyForNode(), that will put the id you give it into the DOM as an attribute to the row. you don't have to have it the same as the node id, but you can do if you decide.

**Comment by dephiros** [comment]
@ceolter I have the node id and want to get the node outside of the cellRenderer context. I would like a more efficient way to get the node object(maybe getNodeFromId in the gridApi) without having to use forEachNode and go through all the nodes. Is it possible or could it be implemented?

**Comment by ceolter** [comment]
nope - the only collection the grid has of the nodes is in the rowModel, which just keeps the nodes in a list. if you want to index by id, then i suggest you keep a map yourself? the grid doens't need it, so it's not a grid responsibility. given you are providing the nodeId's, then you have the perfect callback ```getRowNodeId``` for populating your map.

**Comment by ceolter** [comment]
because the grid doesn't need it, it would be a wast of memory for the grid to keep such a map, given very few people (only one so far) has asked for it :)

**Comment by dephiros** [comment]
got it. Thank you for the response :). I will keep a node reference with my custom checkbox for now

**Comment by nkoterba** [comment]
@ceolter Although this issue is closed, I was trying to determine the best way to handle my use case:

I have updated row data for a specific row from the backend server.  I'd like to just update the row's data and call `api.refreshRows([rowToRefresh])`.

However, the only way to *locate* the row is to call `api.forEachNode` and find the matching node with id.  However, once I find the correct row I can't event short circuit the forEachNode with a `break` statement like a normal javascript array `forEach`.

Do you still recommend just maintaining our own map to find rows based on Ids or is there another more clever way to just find a row based on it's id?

Thanks!

**Comment by a497988** [comment]
+1

**Comment by shijusn** [comment]
Is there a way to early exit/break from forEachNode loop once we find a satisfying node?
return statement doesn't work inside forEachNode()
