### ISSUE TITLE
Set up license without exposing the key in javascript

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#67]
I am looking at the doc for setting up license key. https://www.ag-grid.com/javascript-grid-set-license/index.php

> agGrid.LicenseManager.setLicenseKey("your license key");

Could you please give me a pointer on how to set up the license key without exposing the key in js to public?

**Comment by jameswyse** [comment]
I felt a little uneasy having it in the source too until I realised the validation is only done on the client-side (no mothership in sight)

I think the license system is more to do with keeping us lazy/forgetful developers in check than to prevent theft.

You can see in `LicenseManager.ts` that it just does some simple validation and logs a message to the console if it's invalid. So if you really wanted to you could do something like `agGrid.LicenseManager.prototype.validateLicense = function(){};`. That's probably a breach of the license though so I'd seek permission first!

**Comment by ceolter** [comment]
don't worry about it. due to the nature of javascript we had no choice. if we checked against a license server, then this would cause awful firewall or cors issues. the license key is a simple check we do internally in JavaScript. it's purpose is to make sure you understand what you bought and your developers know what you bought, so if you are a large company and you buy 5 dev licenses for project X, you don't accidentally or unknowingly use it for another project Y or for more developers. if someone wants to pirate ag-Grid Enterprise, they will do it easily, they don't need a key.
