### ISSUE TITLE
[filter set] setFilter does not update the "Select all"

### ISSUE THREAD

**Issue by dzonatan** [ceolter/ag-grid-enterprise#7]
When you set filter via `api.setFilterModel` the "Select all" option of "Set filtering" does not change according to selected values. It always stays `checked`.

There is one more related bug with this. If later you try to set new rows via `api.setRowData` your selected values of that filter will be gone (even with `newRowsAction: 'keep'`). Probably this happens because of [this line](https://github.com/ceolter/ag-grid-enterprise/blob/master/src/setFilter/setFilterModel.ts#L250).

**Comment by ceolter** [comment]
cool, thanks for raising.

**Comment by ceolter** [comment]
tracked by AG-186
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Is it possible that in your case at the end of updating the model you are not calling gridOptions.api.onFilterChanged? You need to call it in order to sync the filters and the grid

The docs have been improved to highlight that after updating a filter through the api this call is necessary. The docs will be available in the next release
