### ISSUE TITLE
Group and Filter on Checkbox column

### ISSUE THREAD

**Issue by uguryilmaz** [ceolter/ag-grid-enterprise#83]
hi, we have boolean fields on our tables. and i define a cell renderer to show checkboxes on grid. but when i want to filter on a check box column, the filter shows like this: 

![image](https://cloud.githubusercontent.com/assets/6348819/19923295/57442e72-a0ef-11e6-89e2-77abffb5d482.png)

1-means empty
2 - blank cell (which is true values)

is there any way to filter the boolean value columns. 

same problems exixts in grouping. 

![image](https://cloud.githubusercontent.com/assets/6348819/19923385/c9dcf540-a0ef-11e6-9c2e-f86ff2ffbdb3.png)

1- group ok
2- but column value in group row is wrong.

**Comment by ceolter** [comment]
i cannot tell whats wrong with your code from the above.

the 'bought' column here uses boolean and set filter:
https://www.ag-grid.com/example.php
so it does work, must be something you are doing wrong.

if you provide a plunker, i can take a look. otherwise, i just see what's wrong.

ps this isn't an issue with ag-Grid (ie it's not requiring something to be changed in ag-grid), so closing the issue.

**Comment by rutykwebit** [comment]
somebody can show the code of filter boolean column

**Comment by AnTechie** [comment]
I am facing the same problem.Check boxes are not aligned with labels and check box is not working for the selected label. In fact when I click on check box ,filtering is happened for the next one.

**Comment by DriLLFreAK100** [comment]
> somebody can show the code of filter boolean column

Happen to be looking for a sample code on boolean filter as well. Anybody has a link to share?

**Comment by cyanerd** [comment]
if someone has same problem - update ur ag-grid packages (ag-grid-community, ag-grid-enterprise) to 27 version
